### ISSUE TITLE
line 119, delay(250)

### ISSUE THREAD

**Issue by aboehmke** [adafruit/Adafruit_MAX31856#4]
Hello,

Thank you for this library. I'm interested in taking temperature measurements every millisecond, but am limited by the 250-millisecond delay in the oneShotTemperature() function. I'm wondering if the delay is necessary. (MEME FIX autocalculate based on oversampling?) 

There're lots of people in online forums wondering about the same thing.

Thank you. 
- Alex

**Comment by ladyada** [comment]
you cannot take a measurement every ms, it takes 200 ms for a conversion see datasheet
https://datasheets.maximintegrated.com/en/ds/MAX31856.pdf

**Comment by riozebratubo** [comment]
Hi, guys. May I suggest a fix for this? The library could have two extra variables: the last time the temperature was asked (like with millis()) and the last reading that was returned. Then the delay could be implemented as this: if at least 250ms passed between the last call and now, make a new measurement; if not, return the last read temperature. This would be non-blocking. Also you could consider changing it to 200ms, since the biggest measurement time on the datasheet (50Hz, one shot) is 185m.

**Comment by riozebratubo** [comment]
Hi, guys. May I suggest a fix for this? The library could have two extra variables: the last time the temperature was asked (like with millis()) and the last reading that was returned. Then the delay could be implemented as this: if at least 250ms passed between the last call and now, make a new measurement; if not, return the last read temperature. This would be non-blocking. Also you could consider changing it to 200ms, since the biggest measurement time on the datasheet (50Hz, one shot) is 185ms.

**Comment by ladyada** [comment]
hiya you can submit a PR for a new non-blocking function if you like

**Comment by riozebratubo** [comment]
Hi. I wrote it. How can I submit the PR? It gives me "remote: Permission to adafruit/Adafruit_MAX31856.git denied to riozebratubo" if I try to push a new branch.

**Comment by ladyada** [comment]
hiya please see
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control

**Comment by riozebratubo** [comment]
Thank you very much!
